apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-frontend
  template:
    metadata:
      labels:
        app: webinar-frontend
    spec:
      containers:
        - name: webinar-frontend
          image: 100xdevs/webinar-frontend:b4a9acabd7d985260ada5bc85175ea2b65dc0893
          ports:
            - containerPort: 4173
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-frontend
spec:
  ports:
    - port: 80
      targetPort: 4173
  selector:
    app: webinar-frontend
