---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: webinar-api-secrets
  namespace: default
spec:
  encryptedData:
    .env: AgAdsbArYowyqybStRcR+lhX9pbE7RKzqmPxrjzhQHEbp46KHaVbK1MnI/DN1giu+TeJwzsLFTe4paVNAkHlfWiOfgWFR68zN5sL05ogpdpEZ4Z01ATuIgf/Qrh2hk1jaqo5u40R/QiV3HDprpAlCI82fO6cMcy7RPNmHMxPf9VKk7uxzgUZbgtQFnq74HRq2Nb2elwIfCwT+5LWvUcHTdThqhssvqd4BOeVb5N+Xou+jtzsQIbMA6JXHugK837HeJlfge+WON0EUC4Zl5HAwoqrcQkb1AH1bzD/l7vNLt5qs7jH6DQZLN2ReZagKF1fPrhURYLPwTSbLlSgv1a92FHrDpdYNXTxALJV5UvEKduoOKJZbWgX99LNpsZM4eiZAtqp/VBkJdlcH1JfUsVy7IGpJkYt4FCMTyB6p65R3w0cD9LY4RhN8kjyz292TJJMxs1j4Bo9Lbzn0SxOVdyuA/hYtw7zwLuhnwRp70quwPsEyzBIgLqK5nKUxYFpbdYkCEmipHHNpcYU71KvdZsLvjBUoYcyOmzUmOFyMZaDy8tkEyZB9+anWG2sf6bQHzlybYPykwhmRtzz5ae1zrrFq2nc1bc0S8rTS/Rh5MxFRfWD19sB7c3ybvOCRZrmMhw607jRY6GAj7/56euLUz+0kB4UgzYx7fO5JRooCitOYMGNOhHqcXUm1ufx7HIvPlrFhf5EpVmjG3aaq2ib3iaGJuPAoUIzkkq7tGSz/lSFba4GGwJrWI3QVcLhkra76DdmRBG5y+LVZQ13/LVI9X4ipt8xiuZeJoQ8Qww7Lk5WibgdRbbVzHxpEWEaVPDke/LTtM0LsqnshhBpxa5PDJ1I3seewjeY1eH4LoIAXuOI/KhnSsLtPCcmYaBaL/DAHR+atsIJyMybex1NXxPL3orFygoKyahEvwN4t1mcLTddeXUgJzMgU4V/hn/+29z6kWPxO3X3a3pbidO0MYxn9fKxdZbGXRw1/+6Nd/RBt5O1ipO/h6YqYG2/3XLKWO080lRd3iff+UH7JZ+5oQB4Fx/YU184Hvf7mr5Tauvlkyyo/H6CoD5PTW2HQ8lfEi6hyeeTeSIrZikQt1G1PF0bEOza1wnvH2Lf+MQSckCIxP1pM/WlfbqoOAmxD0mi1PYz7plQvRP5lCsaHHhXWMLUQwX0jUPwGofvdLMQmR4yj/4uDzVlzFC3Hzl/vtgs+kR8TJD3tLwNhcx1zOJW68moWzYn2ahiMSW//6CCBQnQFH3xvE2S5s5VD9tX+BgNTViwCcoxeUOGLjcUkOuvUG8LTd4fwYNFD1JlMXkt6ojQ+S8C64ASVFo1pOwktaM8WbHp8mVrqGMDBwW90m6mBTBdsgsTyw5H2ymWMk1dluWHpyrPDyXZjxqszGTuiV3u0vfcoUNa9ueWfGAM1/i/vSRgrx7p/ud77YuDS/oeEsJetzCp9j3fGxMtkvutJtFP8YSbBwA985nh/7w=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: webinar-api-secrets
      namespace: default
    type: Opaque
