apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-server
  template:
    metadata:
      labels:
        app: webinar-server
    spec:
      containers:
        - name: webinar-server
          image: 100xdevs/webinar-server:92f470ba04bf996a4978c73438a8b9bed1cf91bd
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/apps/api/.env
              subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: webinar-api-secrets
            items:
              - key: .env
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-server
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: webinar-server
