apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webinar-ws
  template:
    metadata:
      labels:
        app: webinar-ws
    spec:
      containers:
        - name: webinar-ws
          image: 100xdevs/webinar-ws:eaf5e404f0fd74101a4450c5dee5bda0a5176ca4
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: "redis://redis.default.svc.cluster.local:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-ws
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: webinar-ws
