apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-staging
  labels:
    app: cms-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-staging
  template:
    metadata:
      labels:
        app: cms-staging
    spec:
      containers:
        - name: cms-staging
          image: 100xdevs/cms-staging:85b428d74279c93a77a2d1d48c2fd3a11a04e0c1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secret
              mountPath: /usr/src/app/.env
              subPath: .env
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: secret
          secret:
            secretName: cms-staging-secret
            items:
              - key: .env
                path: .env
