apiVersion: apps/v1
kind: Deployment
metadata:
  name: qanda-chatbot-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qanda-chatbot-server
  template:
    metadata:
      labels:
        app: qanda-chatbot-server
    spec:
      containers:
      - name: qanda-server
        image: 100xdevs/qanda-chatbot-server:66aea2add1f411cb65ad29353827d752cba3430b
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
          - name: QDRANT_URL
            value: "http://qdrant-service.default.svc.cluster.local:6333"
        volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: secret
          secret:
            secretName: qanda-chatbot-secrets
            items:
              - key: .env
                path: .env
---
apiVersion: v1
kind: Service
metadata:
  name: qanda-chatbot-server
spec:
  selector:
    app: qanda-chatbot-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001