apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: quiz-frontend
        image: 100xdevs/project-platform-frontend:a7ac87081dedcb4d51cc51f6df7d2f997fa130f3
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: quiz-frontend